package definitions.structures.generic.finitedimensional.finitedimensionalspaces.linearmappings;

public interface IFiniteDimensionalInjectiveLinearMapping extends IFiniteDimensionalLinearMapping {

}
